Repository gugu-book-salon/grokking-simplicity, pull requests merged in 2022-08, with the labels that each got.

#5 add week1
  1주차/띠비/답자랑/우리/answer.js
Labels: Finish

#3 week1/하승 답 제출
  1주차/띠비/답자랑/하승/question.js
Labels: Finish

#7 week1/mizzu 답제출
  1주차/띠비/답자랑/미쭈/question.js
Labels: Finish

#8 답자랑 제출, 테스트 push
  1주차/띠비/답자랑/닭장/question.js
Labels: Refactoring, review required

#6 refactor: refactor given code
  1주차/띠비/답자랑/뻐드렁니/answer.js
Labels: review required

#13 2주차 밍수 과제
  2주차/답자랑/띠비/ming.js
Labels: Finish

#10 Week2/minsu 주간 과제 (밍) 답자랑
  2주차/답자랑/밍/ming.js
Labels: Finish

#12 2주차/woori 2주차 밍수과제 PR
  1주차/띠비/답자랑/우리/answer.ts
  2주차/답자랑/우리/ming.js
Labels: Finish

#14 week2/mizzu 밍수님 과제 제출
  2주차/답자랑/미쭈/ming.js
Labels: Finish

#16 week2/stevy 1차과제
  2주차/답자랑/띠비/stevy.html
  2주차/답자랑/띠비/stevy.js
Labels: 고기많다

#22 week2/mizzu 띠비님 과제 제출
  2주차/답자랑/미쭈/stevy.js
Labels: Finish

#20 refac: 첫번째 리팩토링
  2주차/답자랑/하승/ming.js
  2주차/답자랑/하승/stevy.js
Labels: 고기많다

#19 week2/스티비 1차과제 PR
  2주차/답자랑/우리/stevy.js
Labels: 고기많다

#18 refactor : refactor given code
  2주차/답자랑/버니/ming.js
Labels: 고기많다

#17 week2/띠비님 2주차 주간과제 제출
  2주차/답자랑/ForestLee0513/stevy.js
  2주차/주간과제/stevy.js
Labels: 고기많다

#11 Week2/minsu 띠선생님 과제 답자랑 PR1
  .gitignore
  2주차/답자랑/밍/stevy.js
Labels: 고기많다

#1 week1/ForestLee0513 답안 제출
  1주차/띠비/답자랑/ForestLee0513/question.js
Labels: review required
